[package]
name = "serde-intermediate"
version = "1.0.0"
authors = ["Patryk 'PsichiX' Budzynski <psichix@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1", features = ["derive"] }
petgraph = "0.6"

[dev-dependencies]
serde_json = "1"
serde_yaml = "0.8"
ron = "0.7"
bincode = "1.3"
